### ISSUE TITLE
Questions about the cuda version

### ISSUE THREAD

**Issue by raywzy** [vt-vl-lab/FGVC#1]
Hi,

Thanks for the great work! I met some problems about the cuda version. For RAFT, the requirement version of cuda is 10.1. However, for environment FGVC, cuda >10 is not supported for pytorch 0.4. It will be a littile incovenient if we need to switch the cuda version during inference.

**Comment by gaochen315** [comment]
Sorry for the inconvenience. The current code contains an image inpainting component, which requires Pytorch 0.4.0. I will try to find an image inpainting code that uses a newer Pytorch version.

**Comment by gaochen315** [comment]
Please check the latest code. There is only one environment, i.e., Pytorch 1.6.0, CUDA 10.1.

**Comment by raywzy** [comment]
> Please check the latest code. There is only one environment, i.e., Pytorch 1.6.0, CUDA 10.1.

Thanks for your help!
