### ISSUE TITLE
Index 0 is out of bounds for axis 3 with size 0

### ISSUE THREAD

**Issue by ma-siddiqui** [vt-vl-lab/FGVC#11]
Hi,

I am facing below error while try to run your code. The screen shot is attached.
![Error](https://user-images.githubusercontent.com/42836589/96156761-7fa8b680-0f22-11eb-9fa8-9d9e9dd27aeb.png)

**Comment by HelixNGC7293** [comment]
Got the same issue, is there anyway to fix this?

**Comment by HelixNGC7293** [comment]
It turns out I interrupted the AI process last time, therefore the number of frame files in result folders ('flow' & 'flow_comp') are not the same. delete and retry again solved the issue.

**Comment by gaochen315** [comment]
Close the issue as it was solved.
