### ISSUE TITLE
Q: Planning on removing pyTorch double dependency

### ISSUE THREAD

**Issue by gogobd** [vt-vl-lab/FGVC#12]
Just wanted to ask if you are planning on simplifying the prerequisites by porting to only one version of pyTorch (tentative Nov.)? If that’s not an option maybe containerize the components to make them easier to use?
Impressive results btw. congratulations! And thanks for sharing your work!

**Comment by gaochen315** [comment]
Sorry for the inconvenience. The current code contains an image inpainting component, which requires Pytorch 0.4.0. I will try to find an image inpainting code that uses a newer Pytorch version. Then there will be only one environment.

**Comment by gaochen315** [comment]
Please check the latest code. There is only one environment, i.e., Pytorch 1.6.0, CUDA 10.1. Let me know if you have any questions.
