### ISSUE TITLE
without nonlocal frame flow?

### ISSUE THREAD

**Issue by laoyoutiaotiao** [vt-vl-lab/FGVC#13]
in your code, videoNonLocalFlowF and videoNonLocalFlowB is None?
`get_flowNN_gradient(args,
                                gradient_x_filled,
                                gradient_y_filled,
                                mask,
                                mask_gradient,
                                videoFlowF,
                                videoFlowB,
                                None,
                                None)`

**Comment by zhangqijun** [comment]
in code comment
    # videoNonLocalFlowF: imgH x imgW x 2 x 3 x nFrame
    # videoNonLocalFlowB: imgH x imgW x 2 x 3 x nFrame
in papaer said
For every frame, we compute non-local flow to three additional
frames using the homography-aligned method (Equation 2)

**Comment by gaochen315** [comment]
For the beta version, I disable this function for a faster speed. I will update the code with the non-local flow support. Sorry about that.

**Comment by 21pl** [comment]
did you ever manage to update the code for non-local flow support as ' --Nonlocal ' still produces a type error?
