### ISSUE TITLE
saved images contain green masks

### ISSUE THREAD

**Issue by WeidiXie** [vt-vl-lab/FGVC#16]
Hi, 

May I ask, why this line exists ?
https://github.com/vt-vl-lab/FGVC/blob/9820d3c1a33ba402009ecb1d25e897cbcddc74d5/tool/video_completion.py#L373

and this line 
https://github.com/vt-vl-lab/FGVC/blob/9820d3c1a33ba402009ecb1d25e897cbcddc74d5/tool/video_completion.py#L548

These will make the saved images to have green masks on top.

**Comment by ashirviskas** [comment]
You answered it yourself.


>These will make the saved images to have green masks on top.

**Comment by Andrew-afk** [comment]
Looks like those are leftovers from developers, just mark them as comments.
Maybe they did it for the people who wants the mask only, and didn't remove it.

**Comment by WeidiXie** [comment]
@Andrew-afk  
I see, thanks a lot !

**Comment by gaochen315** [comment]
Andrew is right, this is only for debugging purpose. The green indicates the regions that are not filled after the current iteration. You should not see any green region in the final result, i.e., frame_comp_xxx folder with the largest xxx.

**Comment by gaochen315** [comment]
Close the issue as it was solved.

**Comment by gaochen315** [comment]
Close the issue as it was solved.
