### ISSUE TITLE
Question:File "video_completion.py", line 165

### ISSUE THREAD

**Issue by yunzhongfei** [vt-vl-lab/FGVC#18]
python video_completion.py \
>        --mode video_extrapolation \
>        --path ../data/tennis \
>        --outroot ../result/tennis_extrapolation \
>        --H_scale 2 \
>        --W_scale 2 \
>        --seamless
Pytorch 1.6.0 for flow prediction

Finish Calculating flow.
Traceback (most recent call last):
  File "video_completion.py", line 615, in <module>
    main(args)
  File "video_completion.py", line 578, in main
    video_completion_seamless(args)
  File "video_completion.py", line 418, in video_completion_seamless
    video, corrFlowF, corrFlowB, flow_mask, mask_dilated, start_point, end_point = extrapolation(args, video, corrFlowF, corrFlowB)
  File "video_completion.py", line 165, in extrapolation
    corrFlowF[H_start : H_start + imgH, W_start : W_start + imgW, :] = corrFlowF_ori
ValueError: could not broadcast input array from shape (512,960,2,0) into shape (512,960,2,69)

**Comment by yunzhongfei** [comment]
How can I solve this problem? Thanks

**Comment by yunzhongfei** [comment]
![image](https://user-images.githubusercontent.com/24841272/101270774-5a645600-37b7-11eb-9824-f30cf05a14af.png)

**Comment by gaochen315** [comment]
From the error message you posted, I see either the video or the flow is not loaded correctly. Can you check the dimension of `video`, `corrFlowF`, and `corrFlowB`?

**Comment by yunzhongfei** [comment]
> From the error message you posted, I see either the video or the flow is not loaded correctly. Can you check the dimension of `video`, `corrFlowF`, and `corrFlowB`?

![image](https://user-images.githubusercontent.com/24841272/101271356-e167fd00-37bc-11eb-8ed6-a90d2c33ab06.png)

**Comment by yunzhongfei** [comment]
![image](https://user-images.githubusercontent.com/24841272/101271362-eaf16500-37bc-11eb-85d7-b1c0e60598f0.png)

**Comment by yunzhongfei** [comment]
python video_completion.py        --mode object_removal        --path ../data/tennis        --path_mask ../data/tennis_mask        --outroot ../result/tennis_removal        --seamless
Pytorch 1.6.0 for flow prediction

Finish Calculating flow.
Please switch to Pytorch 0.4.0




python video_completion.py \
>        --mode object_removal \
>        --path ../data/tennis \
>        --path_mask ../data/tennis_mask \
>        --outroot ../result/tennis_removal \
>        --seamless
Pytorch 1.6.0 for flow prediction

Finish Calculating flow.
Please switch to Pytorch 0.4.0

**Comment by yunzhongfei** [comment]
I feel like there's something wrong with the previous step. @gaochen315

**Comment by gaochen315** [comment]
It seems like you don't deactivate the `raft` environment by `conda deactivate`. Try deactivating it first and then activate the second environment.

**Comment by gaochen315** [comment]
Please check the latest code. There is only one environment, i.e., Pytorch 1.6.0, CUDA 10.1. Let me know if you have any questions.

**Comment by gaochen315** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you have other questions.

Thank you!

**Comment by yunzhongfei** [comment]
ok, thank you very much.
