### ISSUE TITLE
Can this technology transfer to different feild video, such as medical video?

### ISSUE THREAD

**Issue by JialinKang** [vt-vl-lab/FGVC#25]

**Comment by gaochen315** [comment]
Our method relies on the predicted optical flow. I don't think RAFT is pre-trained on a medical dataset. Thus, the completion results might be degraded. 

But you still can run the algorithm on an arbitrary video.

**Comment by gaochen315** [comment]
I’m closing this issue because it has been inactive for a month. Please reopen if you have other questions.

Thank you!
