### ISSUE TITLE
Process killed after memory allocation

### ISSUE THREAD

**Issue by Dolamin792** [vt-vl-lab/FGVC#27]
I'm running it on Google Colab pro (Max ram settings)
Processing 256 frames at 640x480 

> Calculating backward flow 146 <---> 147 
Finish flow prediction.
Completing backward flow 118 <---> 119tcmalloc: large alloc 1091174400 bytes == 0xf3156000 @  0x7fe0f8733001 0x7fe0eda164ff 0x7fe0eda66ab8 0x7fe0eda6abb7 0x7fe0edb09003 0x50a4a5 0x50cc96 0x5095c8 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x50ad03 0x634e72 0x634f27 0x6386df 0x639281 0x4b0dc0 0x7fe0f832ebf7 0x5b259a
tcmalloc: large alloc 1639604224 bytes == 0x7fdf0c268000 @  0x7fe0f87311e7 0x7fe0eda1641e 0x7fe0eda66bdb 0x7fe0eda66c78 0x7fe0edab7c39 0x7fe0edb05f70 0x7fe0edb06a6b 0x566fae 0x59fd0e 0x7fe0eda53ea7 0x50a12f 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x50ad03 0x634e72 0x634f27 0x6386df 0x639281
tcmalloc: large alloc 1639604224 bytes == 0x7fde69622000 @  0x7fe0f87311e7 0x7fe0eda1641e 0x7fe0eda66bdb 0x7fe0eda66c78 0x7fe0edab7c39 0x7fe0edb05f70 0x7fe0edb06a6b 0x566fae 0x59fd0e 0x7fe0eda53ea7 0x50a12f 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x50ad03 0x634e72 0x634f27 0x6386df 0x639281
bash: line 7:   325 Killed                  python3 video_completion.py --mode video_extrapolation --path ../demo/papa --outroot ../result/tennis_extrapolation --W_scale 2 --seamless

**Comment by gaochen315** [comment]
It seems like an OOM issue. Maybe try 50 frames first? You may want to disable --seamless for a faster speed.

**Comment by gaochen315** [comment]
I’m closing this issue because it has been inactive for a month. Please reopen if you still encounter this issue.

Thank you!
