### ISSUE TITLE
extrapolation artifacts

### ISSUE THREAD

**Issue by ak9250** [vt-vl-lab/FGVC#31]
in google colab running extrapolation on the first example frame tennis has artifacts
![49e6bdb8-d461-466c-b131-5ee1ea41a651](https://user-images.githubusercontent.com/6818285/104140760-fcf89180-5380-11eb-9528-bac3d8b9cf17.png)

**Comment by ak9250** [comment]
@gaochen315 also artifacts are present with or without --seamless

**Comment by ak9250** [comment]
@gaochen315 any update on this?

**Comment by gaochen315** [comment]
This is expected. For example, the top right region is never revealed in the video. So we have to count on the single image completion. The current image completion is trained for inpainting, so it will perform poorly on image outpainting. Hope this helps.

**Comment by ak9250** [comment]
@gaochen315 ok thanks
