### ISSUE TITLE
Near zero GPU load

### ISSUE THREAD

**Issue by coldfir3** [vt-vl-lab/FGVC#34]
I am having almost zero % GPU load when running the same code from colab. Any ideas what might be causing it?
![f](https://user-images.githubusercontent.com/13731681/109321841-613bbb80-7830-11eb-9a28-d86fe98461df.gif)

**Comment by brunomsantiago** [comment]
The gpu intensive neural networks are just part of the algorithm. The video completion code has lots of cpu-intensive operations using numpy, scipy, skimage, opencv and pillow.
Can't say for sure, but I belive the video completion tool spend most of time on cpu operations.

**Comment by gaochen315** [comment]
Thanks, @brunomsantiago. You are right. Our method uses GPU to predict the flow, complete the flow edge, and perform per-frame inpainting. But the majority of the code is about content propagation, which is pure CPU work.
