### ISSUE TITLE
RuntimeError: CUDA out of memory on Colab

### ISSUE THREAD

**Issue by AnimeshMaheshwari22** [vt-vl-lab/FGVC#40]
I am using some different images and getting this error on Colab. I would be grateful to receive some advice on this. Thanks!

**Comment by lec0dex** [comment]
Please, take a look at my fork [https://github.com/lec0dex/FGVC](https://github.com/lec0dex/FGVC). The implementation on that fork uses more of the disk and reduce the memory requirements, both GPU and CPU-RAM.

If the authors finds that it's somehow useful I can make a pull request.
