### ISSUE TITLE
How can I train my own dataset

### ISSUE THREAD

**Issue by a695649350** [vt-vl-lab/FGVC#42]
I saw 3 pre-trained models. But I don't know how to train with my own dataset.

**Comment by gaochen315** [comment]
Hi, you don't need to train the model for your dataset. Just set up the environment according to the instruction, and run [this](https://github.com/vt-vl-lab/FGVC#quick-start).

Let me know if you have any questions.

**Comment by a695649350** [comment]
> Hi, you don't need to train the model for your dataset. Just set up the environment according to the instruction, and run [this](https://github.com/vt-vl-lab/FGVC#quick-start).
> 
> Let me know if you have any questions.

Maybe I misunderstood the actual principle of this project, still thanks for the great job

**Comment by a695649350** [comment]
> Hi, you don't need to train the model for your dataset. Just set up the environment according to the instruction, and run [this](https://github.com/vt-vl-lab/FGVC#quick-start).
> 
> Let me know if you have any questions.

I want to know how to train the deepfill weight? The image inpainting part use Deepfillv1, but it is hard for me to train a suitable weight file

**Comment by gaochen315** [comment]
I didn't train Deepfillv1 myself. I use the pre-trained weight. Why do you need to train Deepfillv1 yourself? Do you have a specific dataset that requires fine-tuning?

**Comment by a695649350** [comment]
> I didn't train Deepfillv1 myself. I use the pre-trained weight. Why do you need to train Deepfillv1 yourself? Do you have a specific dataset that requires fine-tuning?

It seems like if the inpainting area which does not appear in the whole video will not be good as expected.

So I think this part may depend on the training dataset.

**Comment by dragen1860** [comment]
@gaochen315 I can not find the training code? please help me, thank you.
