### ISSUE TITLE
How to get videoNonLocalFlowF and videoNonLocalFlowB?

### ISSUE THREAD

**Issue by weifj0212** [vt-vl-lab/FGVC#45]
Thanks for sharing your impressive work!
I was trying to find the non-local flow computation, but how to get these parameters of videoNonLocalFlowF and videoNonLocalFlowB  in get_flowNN.py? Could you please give me some guidance for these parameters?

**Comment by gaochen315** [comment]
Hi, 

Currently, I disable the usage of the non-local flow for a faster speed. But I do provide the non-local implementation in get_flowNN.py so it should be easy to use. 

Basically, for each frame, you need to compute the flow to the first, middle, and last frame. And then, you can pass them to get_flowNN. Let me know if this helps.

**Comment by lec0dex** [comment]
Do I also need to go thought flow completion?

**Comment by gaochen315** [comment]
Hey guys,

Really sorry for the late reply. Now the code supports non-local flow. You can enable the `--Nonlocal` flag.

Please note that I haven't thoroughly tested the correctness of the non-local flow (this codebase is different from the one I used for ECCV).

Hope this helps. Please let me know if there is anything I can help with.
