### ISSUE TITLE
"tcmalloc: large alloc" error an image sequence of 228 fullhd jpg files, on Colab

### ISSUE THREAD

**Issue by richuntt** [vt-vl-lab/FGVC#47]
am I asking too much?
I'm trying to execute a sequence of 228 fullhd jpg files on Colab.
I get this message:
```
tcmalloc: large alloc 5673369600 bytes == 0x55b4a2bdc000 @  0x7fa98570bb6b 0x7fa98572b379 0x7fa922e4892e 0x7fa922e4a946 0x7fa95b226bb3 0x7fa95acdb17a 0x7fa95acdc293 0x7fa95b1dcedf 0x7fa95ad6a6a6 0x7fa95ad6b7b0 0x7fa95afc21c9 0x7fa95a963689 0x7fa95b0a1919 0x7fa95ad6d09b 0x7fa95b157a08 0x7fa95a963689 0x7fa95b0a1709 0x7fa95ad62d1d 0x7fa95b161dc8 0x7fa95a963689 0x7fa95b0a1b29 0x7fa95cddb347 0x7fa95a963689 0x7fa95b0a1b29 0x7fa96a73b746 0x55b2ce0770e4 0x55b2ce076de0 0x55b2ce0eb6f5 0x55b2ce07869a 0x55b2ce0e6a45 0x55b2ce07869a
bash: line 7:  1201 Killed                  python3 video_completion.py --mode object_removal --path ../kepescap/kepesc --path_mask ../kepescap/kepesc_mask --outroot ../result/kep_removal --seamless
```

**Comment by gaochen315** [comment]
Hi, 

It seems like you are processing too many frames. You can subsample frames and reduce the resolution a little bit. For example, sample every 4 frames, and reduce the resolution to 540p. Let me know if this helps.

**Comment by richuntt** [comment]
thank you for your answer!
-is it something I can do with code on Colab or do I have to do it by hand?
-is it possible to compute all that data on your suggested settings (low def/framerate) and apply it to mine (high def/framerate) to get the desired result?
-are you planning on optimizing your fantastic work to get it to the point of something that can be used in a workflow or are you working on something else now?
thank you!

**Comment by richuntt** [comment]
So i've tried by reducing the resolution and feeding it 1 frame out of 3 and it did work!
The result is quite impressive considering the complexity of the footage but unfortunatelly it is a low res and laggy result (obviously).
Allow me to reitirate my question, do you have any plan of optimizing this great tool or should we try to manage with it as it is?

Thank you

**Comment by gaochen315** [comment]
Hi, currently we don't have plans to further optimize the code. However, there are several parts that can be significantly improved to handle high-resolution video. The current code is mainly for research, so I on purpose makes it less efficient but easier to debug. If time allowed, I may optimize the code further.

**Comment by richuntt** [comment]
Hi,
Thank you for your insight, I understand better now.
Well I hope that time will be allowed to you, your work is really astonishing.
Best,
