### ISSUE TITLE
Can we use the cv2.remap to replace get_flowNN color propagation function?

### ISSUE THREAD

**Issue by JialinKang** [vt-vl-lab/FGVC#51]
just like this [link](https://stackoverflow.com/questions/44041157/how-to-warp-the-later-frame-to-previous-frame-using-optical-flow-image)

**Comment by JialinKang** [comment]
because I just want to use the adjacent frames through optical flow

**Comment by gaochen315** [comment]
Sorry for the late reply.

If a video only contains two frames, then our code is identical to flow warping. However, if a video has more than two frames, you have to CHAIN the flow vectors first, and then pull the color from the known region. In other words, the flow neighbor does not necessarily locate in adjacent frames.

Hope this helps.



If you only have two frames, then 
If your want to
