### ISSUE TITLE
' --Nonlocal ' in video_completion.py results in error

### ISSUE THREAD

**Issue by 21pl** [vt-vl-lab/FGVC#52]
Traceback (most recent call last):
  File "video_completion.py", line 613, in <module>
    main(args)
  File "video_completion.py", line 576, in main
    video_completion_seamless(args)
  File "video_completion.py", line 510, in video_completion_seamless
    None)
  File "/content/FGVC/tool/get_flowNN_gradient.py", line 440, in get_flowNN_gradient
    videoNonLocalFlowB[:, :, :, 0, indFrame],
TypeError: 'NoneType' object is not subscriptable

**Comment by habijung** [comment]
**I got a same problem.**

In my case,

`python video_completion.py`
`--seamless`
`--edge_guide`
`--mode object_removal`
`--path '{% path %}'`
`--path_mask '{% path_mask %}'`
`--outroot '{% outroot %}'`
`--Nonlocal true`
`--mixed_precision`

and the result is also
`File "~\FGVC\tool\get_flowNN_gradient.py", line 440, in get_flowNN_gradient`
`    videoNonLocalFlowB[:, :, :, 0, indFrame],`
`TypeError: 'NoneType' object is not subscriptable`

In `get_flowNN_gradient.py`, there is not defined `videoNonLocalFlowB` & `videoNonLocalFlowF`.
**How can I get this value?**

**Comment by gaochen315** [comment]
Hi @21pl,

Sorry for the late reply. Now the code supports non-local flow. You can enable the `--Nonlocal` flag.

Please note that I haven't thoroughly tested the correctness of the non-local flow (this codebase is different from the one I used for ECCV).

Hope this helps. Please let me know if there is anything I can help with.
