### ISSUE TITLE
How can I train a new model on a different dataset?

### ISSUE THREAD

**Issue by Eason-Great** [vt-vl-lab/FGVC#59]
Hello, thanks for the excellent work.
I want to test the performance of another dataset, so I may need to train a new model. Trainable parameters only exit in EdgeConnect and RAFT, right? So it means what I should do is to train EdgeConnect on the new dataset?
Thanks for your help!

**Comment by gaochen315** [comment]
What is this dataset about? In general, you do not need to re-train the models. But if your dataset is from a different domain, e.g., medical, you may have to re-train the models.

**Comment by Eason-Great** [comment]
Yean,it's exactly from a different domain. So I want to know how to train a new model. It seems that you don't give the reference for training.
Thanks!

**Comment by gaochen315** [comment]
For training RAFT, you can refer to the instruction [here](https://github.com/princeton-vl/RAFT#training).

What if you directly run the code on your dataset? Is the result very bad?
