### ISSUE TITLE
edge_guide flag

### ISSUE THREAD

**Issue by ewwnage** [vt-vl-lab/FGVC#64]
in [video_completion.py ](https://github.com/vt-vl-lab/FGVC/blob/1b44ece001c8888a72eabd32a58ade0ad24f87a2/tool/video_completion.py#L508) is checked if the edge_guide flag was set. By default it is not so I assume that the edge connect network is not implemented in the default inference path?
Is the EdgeConnect only used if this flag is set? What happens if it's not set? Does the network simply just don't complete flow edges?

Thanks in advance

**Comment by gaochen315** [comment]
Edge-guided flow completion is implemented. But we can choose to use it or not.  If `edge_guide ` is flagged, we'll use it. If not, we'll just use diffusion for flow completion.

My experience is: it is not needed for most object removal cases. Incorrect flow edges will cause problems in flow completion, which will affect the final video completion.

Hope this helps. Let me know if you have other questions.
