### ISSUE TITLE
Will it have a Windows version for CUDA 10.2?

### ISSUE THREAD

**Issue by HelixNGC7293** [vt-vl-lab/FGVC#8]
Thank you for this great project! My GPU is 2080ti with CUDA10.2. Therefore I'm wondering if it is gonna support windows os somehow in the future?

Thank you again!

**Comment by ashirviskas** [comment]
You should be able to switch the installed CUDA version. See: https://stackoverflow.com/questions/51470527/install-cuda-8-and-cuda-9-in-windows

**Comment by HelixNGC7293** [comment]
> You should be able to switch the installed CUDA version. See: https://stackoverflow.com/questions/51470527/install-cuda-8-and-cuda-9-in-windows

Thank you!

**Comment by gaochen315** [comment]
Please check the latest code, which supports Pytorch 1.6.0 and CUDA 10.1. Let me know if you have any questions.
